services:
  budget-planner-postgres:
    container_name: budget-planner-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "2000:5432"
    volumes:
      - budget-planner-db:/var/lib/postgresql/data
    networks:
     - common_network
  budget-planner-backend:
    container_name: budget-planner-backend
    image: nodirshox/budget-planner-backend:latest
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - DEVICE_ID=${DEVICE_ID}
      - PASSWORD=${PASSWORD}
      - ACCOUNT_ID=${ACCOUNT_ID}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "2001:4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.budget-planner-backend.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.budget-planner-backend.entrypoints=websecure"
      - "traefik.http.routers.budget-planner-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.budget-planner-backend.loadbalancer.server.port=4000"
      - "traefik.docker.network=de_default"
    networks:
     - common_network
volumes:
  budget-planner-db:
    driver: local
networks:
 common_network:
  external: true
  name: common_network