version: "3.1"

services:
  budget-planner-postgres:
    container_name: budget-planner-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "2000:5432"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgres.rule=Host(`${POSTGRES_DOMAIN}`)"
      - "traefik.http.routers.postgres.entrypoints=websecure"
      - "traefik.http.routers.postgres.tls.certresolver=letsencrypt"
      - "traefik.http.services.postgres.loadbalancer.server.port=5432"
      - "traefik.docker.network=ta_default"
    volumes:
      - budget-planner-db:/var/lib/postgresql/data
    networks:
     - common_network
  budget-planner-backend:
    container_name: budget-planner-backend
    image: nodirshox/budget-planner-backend:latest
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "2001:4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
      - "traefik.docker.network=ta_default"
    networks:
     - common_network
volumes:
  budget-planner-db:
    driver: local
networks:
 common_network:
  external: true
  name: common_network